const appTypes = {
  GET_BUCKET_LIST_REQUEST: "GET_BUCKET_LIST_REQUEST",
  GET_BUCKET_LIST_SUCCESS: "GET_BUCKET_LIST_SUCCESS",
  GET_BUCKET_LIST_ERROR: "GET_BUCKET_LIST_ERROR",

  CREATE_BUCKET_LIST_REQUEST: "CREATE_BUCKET_LIST_REQUEST",
  CREATE_BUCKET_LIST_SUCCESS: "CREATE_BUCKET_LIST_SUCCESS",
  CREATE_BUCKET_LIST_ERROR: "CREATE_BUCKET_LIST_ERROR",

  UPDATE_BUCKET_LIST_REQUEST: "UPDATE_BUCKET_LIST_REQUEST",
  UPDATE_BUCKET_LIST_SUCCESS: "UPDATE_BUCKET_LIST_SUCCESS",
  UPDATE_BUCKET_LIST_ERROR: "UPDATE_BUCKET_LIST_ERROR",

  DELETE_BUCKET_LIST_REQUEST: "DELETE_BUCKET_LIST_REQUEST",
  DELETE_BUCKET_LIST_SUCCESS: "DELETE_BUCKET_LIST_SUCCESS",
  DELETE_BUCKET_LIST_ERROR: "DELETE_BUCKET_LIST_ERROR",

  CREATE_TODO_REQUEST: "CREATE_TODO_REQUEST",
  CREATE_TODO_SUCCESS: "CREATE_TODO_SUCCESS",
  CREATE_TODO_ERROR: "CREATE_TODO_ERROR",

  UPDATE_TODO_REQUEST: "UPDATE_TODO_REQUEST",
  UPDATE_TODO_SUCCESS: "UPDATE_TODO_SUCCESS",
  UPDATE_TODO_ERROR: "UPDATE_TODO_ERROR",

  DELETE_TODO_REQUEST: "DELETE_TODO_REQUEST",
  DELETE_TODO_SUCCESS: "DELETE_TODO_SUCCESS",
  DELETE_TODO_ERROR: "DELETE_TODO_ERROR",

  GET_TODO_REQUEST: "GET_TODO_REQUEST",
  GET_TODO_SUCCESS: "GET_TODO_SUCCESS",
  GET_TODO_ERROR: "GET_TODO_ERROR"
};

export default appTypes;
