const appTypes = {
  GET_MENTOR_LIST_REQUEST: "GET_MENTOR_LIST_REQUEST",
  GET_MENTOR_LIST_SUCCESS: "GET_MENTOR_LIST_SUCCESS",
  GET_MENTOR_LIST_ERROR: "GET_MENTOR_LIST_ERROR",

  ADD_MENTOR_REQUEST: "ADD_MENTOR_REQUEST",
  ADD_MENTOR_SUCCESS: "ADD_MENTOR_SUCCESS",
  ADD_MENTOR_ERROR: "ADD_MENTOR_ERROR",

  DELETE_MENTOR_REQUEST: "DELETE_MENTOR_REQUEST",
  DELETE_MENTOR_SUCCESS: "DELETE_MENTOR_SUCCESS",
  DELETE_MENTOR_ERROR: "DELETE_MENTOR_ERROR",

  ADD_TASK_REQUEST: "ADD_TASK_REQUEST",
  ADD_TASK_SUCCESS: "ADD_TASK_SUCCESS",
  ADD_TASK_ERROR: "ADD_TASK_ERROR",

  DELETE_TASK_REQUEST: "DELETE_TASK_REQUEST",
  DELETE_TASK_SUCCESS: "DELETE_TASK_SUCCESS",
  DELETE_TASK_ERROR: "DELETE_TASK_ERROR",

  UPDATE_ACTIVE_MENTOR: "UPDATE_ACTIVE_MENTOR"
};

export default appTypes;
